### ISSUE TITLE
Django 2 Checklist

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/wagtailstreamforms#53]
When django 2 and wagtail 2 are released do last checks and publish

- [x] Update setup.py
- [x] Update tox.ini
- [x] Run tests and fix any issues
- [x] Make sure example site works
- [x] Publish
