### ISSUE TITLE
3.0 todo list

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/wagtailstreamforms#78]
- [x] Rename form.name to form.title and loose extra js
- [x] document widget attrs
- [x] Provide management command to prune submissions after x days
- [x] Dont break save submission if file field is used
- [x] Handling the files in a file field
- [x] Empty top value in dropdown
- [x] document usage incl email hook
- [x] update README
- [x] update docs index
- [x] replace invalid screenshots
- [x] Add notice advising upgrade not possible

**Comment by stuartaccent** [comment]
We wont be supporting upgrade from 2 as there is too much involved :(
